// Generated by CoffeeScript 1.6.2
(function() {
  var draw, drawGrid, game, init, update;

  drawGrid = function() {
    var x, y, _i, _j, _ref, _ref1, _ref2, _ref3;

    game.context.beginPath();
    for (x = _i = _ref = game.board.x, _ref1 = game.board.w; _i < _ref1; x = _i += 20) {
      game.context.moveTo(x + .5, game.board.y + .5);
      game.context.lineTo(x + .5, game.board.h + .5);
    }
    for (y = _j = _ref2 = game.board.y, _ref3 = game.board.h; _j <= _ref3; y = _j += 20) {
      game.context.moveTo(game.board.x + .5, y + .5);
      game.context.lineTo(game.board.w + .5, y + .5);
    }
    game.context.stroke();
    return game.context.closePath();
  };

  draw = function() {
    return drawGrid();
  };

  update = function() {};

  init = function() {
    var canvas, context, game;

    canvas = document.createElement('canvas');
    canvas.width = 800;
    canvas.height = 401;
    canvas.x = 0;
    canvas.y = 0;
    document.body.appendChild(canvas);
    context = canvas.getContext('2d');
    return game = {
      canvas: canvas,
      context: context,
      board: {
        x: 0,
        y: 0,
        w: 601,
        h: 401
      },
      start: function() {
        setTimeout(draw, 10);
        return setTimeout(update, 1);
      }
    };
  };

  window.game = game = init();

  game.start();

}).call(this);

/*
//@ sourceMappingURL=game.map
*/
